name: Publish Release
on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@10c66d66e558b37df92e2a8ec5321218a6547b04
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      generate: true
